# Generated by Django 4.1.2 on 2026-06-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_movie_created_at_alter_movie_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGOUT', 'Logout'), ('MOVIE_CREATE', 'Movie Created'), ('MOVIE_UPDATE', 'Movie Updated'), ('MOVIE_DELETE', 'Movie Deleted'), ('REVIEW_CREATE', 'Review Created'), ('REVIEW_UPDATE', 'Review Updated'), ('REVIEW_DELETE', 'Review Deleted'), ('AUTHZ_FAILED', 'Failed Authorization Attempt'), ('ADMIN_ACTION', 'Administrator Action')], db_index=True, max_length=20)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('affected_object_id', models.IntegerField(blank=True, null=True)),
                ('affected_object_type', models.CharField(blank=True, max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action_details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
